#pragma once

/* Main Loop */
enum OPMODE
{
	OP_MODE_RECV = 0, OP_MODE_SEND, OP_MODE_ACCEPT, OP_RANDOM_MOVE, OP_PLAYER_MOVE_NOTIFY, OP_MODE_ATTACK,
	OP_ORC_MOVE, OP_ELF_MOVE, OP_BOSS_MOVE, OP_MONSTER_DIE, OP_MONSTER_ATTACK, OP_MODE_END
};

/* OBJECT STATUS */
enum STATUS { ST_ACTIVE = 0, ST_STOP, ST_ATTACK, ST_DEAD, AT_END };

